website/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'sdfewerwerwerwer'
    from .auth import auth
    app.register_blueprint(auth, url_prefix = '/')
    from .views import views
    app.register_blueprint(views, url_prefix = '/')

    return app

website/auth.py
from flask import Blueprint, render_template

auth = Blueprint('auth' , __name__)

@auth.route('/login')
def login():
    return  render_template('login.html')

website/views.py
from flask import Blueprint , render_template , request
import pandas as pd
import csv
from os.path import join, dirname, realpath
import os
from collections import OrderedDict
from operator import getitem
import math
import gensim
import nltk
from nltk import word_tokenize
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
views = Blueprint('views' , __name__)

@views.route('/')
@views.route('/login')
def home():
    return  render_template('login.html')

@views.route('/Dashboard')
def Dashboard():
    return  render_template('Dashboard.html')    

@views.route('/Embezzlement')
def Embezzlement():
    return  render_template('Embezzlement.html')   

@views.route('/EntityPreview_NEW')
def EntityPreview_NEW():
    return  render_template('EntityPreview_NEW.html')   

@views.route('/House_Theft')
def House_Theft():
    return  render_template('House_Theft.html')  

@views.route('/MainResult' , methods=['GET', 'POST'])
def MainResult():
    if request.method == 'POST':
        Report_title  = request.form.get('Report_title')
        Reporter_name  =request.form.get('Reporter_name')
        Incident_date  =  request.form.get('Incident_date')
        time  =  request.form.get('time')
        City  = request.form.get('City')
        Day  =  request.form.get('Day')
        Place  =  request.form.get('Place')
        District  = request.form.get('District')
        street  = request.form.get('street')
        loot  = request.form.get('loot')
        loot_description  = request.form.get('loot_description')
        is_camera  =  request.form.get('is_camera')
        loot_methodology  =  request.form.get('loot_methodology')
        estemated_loot_value  =  request.form.get('estemated_loot_value')
        Accused =  request.form.get('accused_name')
        weapon_existens  = request.form.get('weapon_existens')
        Accuseds_number  =  request.form.get('Accuseds_number')
        number_of_accused  = request.form.get('number_of_accused')
        Accused_description  = request.form.get('Accused_description')
        skin_colour  =  request.form.get('skin_colour')  
        Nationality  =  request.form.get('Nationality')   
        Age  =  request.form.get('Age')   
        accused_body  = request.form.get('accused_body')
        Report_content =  request.form.get('Report_content')
        known_vehicle =  request.form.get('known_vehicle')
 

        path1 = join(dirname(realpath(__file__)), 'static/Data', 'datatest.txt')
        text_file = open(path1, "r")
        lines = text_file.readlines()
        text_file.close()

        path = join(dirname(realpath(__file__)), 'static/Data', 'data_1111111.csv')
        #print(path) # /var/www/public_html/app/myfile.json
        data = pd.read_csv(path, nrows=500)
        data = data.to_dict('records')
        def tagged_document(list_of_list_of_words):
            for i, list_of_words in enumerate(list_of_list_of_words):
                yield gensim.models.doc2vec.TaggedDocument(list_of_words, [i])
        data_for_training = list(tagged_document(data[:999]))
        model = gensim.models.doc2vec.Doc2Vec(vector_size = 40, min_count = 2, epochs = 30)
        model.build_vocab(data_for_training)
        model.train(data_for_training, total_examples = model.corpus_count, epochs = model.epochs )
        #print(model.infer_vector("نا فاطمة المالك أرغب بالتبليغ عن حادثة سرقة منزل تمت السرقة في تاريخ 44402 الوقت 03:".split()))
        print(model.docvecs.most_similar([10]))
        token = Report_content.split()
        new_vector  = model.infer_vector(doc_words=token, alpha=0.025,min_alpha=0.001)




        path = join(dirname(realpath(__file__)), 'static/Data', 'data_1111111.csv')
        #print(path) # /var/www/public_html/app/myfile.json
        data = pd.read_csv(path, nrows=500)
        data = data.to_dict('records')
       # print(data[0])
        new = {
        'Report_title':  Report_title ,
        'Reporter_name': Reporter_name ,
        'Incident_date': Incident_date,
        'Day': Day,
        'time': time,
        'Place': Place,
        'City': City,
        'District': District,
        'street': street,
        'loot': loot,
        'loot_description': loot_description,
        'is_camera': is_camera,
        'loot_methodology': loot_methodology ,
        'estemated_loot_value': estemated_loot_value,
        'Accused': Accused,
        'weapon_existens': weapon_existens,
        'Accuseds_number': Accuseds_number,
        'Accused_description': Accused_description,
        'skin_colour': skin_colour,
        'Nationality':  Nationality ,
        'Age':Age,
        'known_vehicle': known_vehicle,
        'accused_body': accused_body,
        'Report_content':Report_content}

        y = 0

        res_d = {y : {}}

        for key in data:
            # print(key)
            row = key
            res = False
            count = 0
            similar_feileds = []
            for key in new:
                if new.get(key) == row.get(key):
                    res = True
                    count = count + 1
                    similar_feileds.append(key)

            similarity = count/ len(new)            
            if(similarity != 0):
                print('break')
                res_d[y] = {}
                res_d[y]['similarity'] = similarity
                res_d[y]['Report_content'] = row["Report_content"]
                #print(res_d[y])
                #print(y)
                y =  y + 1
                
            #print("first")
            #print(res_d)
        # print("second")
        # print(res_d)
        res = OrderedDict(sorted(res_d.items(),reverse=True, key = lambda x: getitem(x[1], 'similarity')))
        sim1 = res[0]['similarity']
        sim1 = round(sim1 , 4)
        report1 = res[0]['Report_content']
        sim2 = res[1]['similarity']
        sim2 = round(sim2 , 4)
        report2 = res[1]['Report_content']
        sim3 = res[2]['similarity']
        sim3 = round(sim3 , 4)
        report3 = res[2]['Report_content']
        sim4 = res[3]['similarity']
        sim4 = round(sim4 , 4)
        report4 = res[3]['Report_content']
        sim5 = res[4]['similarity']
        sim5 = round(sim5 , 4)
        report5 = res[4]['Report_content']

        return  render_template('MainResult.html' , brv = Report_content, val1_S = sim1 , val1_r = report1 ,val2_S = sim2 , val2_r = report2 , val3_S = sim3 ,val3_r = report3, val4_S = sim4 ,val4_r = report4,  val5_S = sim5 ,val5_r = report5 )    
    return  render_template('MainResult.html' )  

@views.route('/Preview_NEW_Embezzlement')
def Preview_NEW_Embezzlement():
    return  render_template('Preview_NEW_Embezzlement.html')  

@views.route('/Preview_NEW_House_Theft')
def Preview_NEW_House_Theft():
    return  render_template('Preview_NEW_House_Theft.html')  

@views.route('/ProceedingPreview_OLD')
def ProceedingPreview_OLD():
    return  render_template('Preview_NEW_House_Theft.html')  

@views.route('/ReportContent')
def ReportContent():
    return  render_template('ReportContent.html') 

@views.route('/AdvancedResults')
def AdvancedResults():
    return  render_template('AdvancedResults.html')   

    

website/templates/EntityPreview_NEW.html
<!DOCTYPE html>
<html lang="ar">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="./static/Images/icon.png" />
    <title>Smart Detective</title>
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="./static/Style/style.css" />
  </head>

  <body dir="rtl">
    <header>
      <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
          <div class="navbar-brand d-flex align-items-center">
            <a href="#">
              <img
                src="./static/Images/logo.svg"
                alt="logo"
                class="d-inline-block align-text-top img-fluid"
              />
            </a>
            <div
              class="mx-2"
              style="height: 60px; width: 2px; background-color: #fff"
            ></div>
            <h3>استعراض المحضر المتشابه</h3>
          </div>
          <div class="d-flex nav-icons me-auto">
            <a href="#" class="mx-2">
              <span class="material-icons"> person </span>
            </a>
            <a href="./static/Login.html">
              <span class="material-icons"> settings_power </span>
            </a>
          </div>
        </div>
      </nav>
    </header>
    <main class="container pt-3">
      <div class="d-flex" style="margin-top: 3rem">
        <div
          class="button-perview"
          style="flex: 1; border-radius: 0 10px 10px 0"
        >
          <p class="text-center my-2">جميع الكيانات</p>
        </div>
        <div
          class="button-perview active-perview"
          style="flex: 1; border-radius: 10px 0px 0px 10px"
        >
          <p class="text-center my-2">الكيانات المتشابهة</p>
        </div>
      </div>
      <div class="row my-4">
        <div class="col-4">
          <p style="color: #32a05f; font-family: Bold" class="mx-5 px-3">
            الكيان
          </p>
        </div>
        <div class="col-4">
          <p class="text-center" style="color: #32a05f; font-family: Bold">
            المحضر المدخل
          </p>
        </div>
        <div class="col-4">
          <p class="text-center" style="color: #32a05f; font-family: Bold">
            المحضر المتشابه
          </p>
        </div>
      </div>

      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="
          border-bottom: 1px solid #d3d3d3;
          padding-bottom: 5px;
          margin-bottom: 10px;
        "
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>
      <div
        class="row text-center mx-5"
        style="padding-bottom: 5px; margin-bottom: 10px"
      >
        <div class="col-4"><p>Field</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
        <div class="col-4"><p class="text-center">TEXT</p></div>
      </div>

      <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-success">عودة</button>
      </div>
    </main>
    <footer style="margin-top: 2rem">
      <div class="container-fluid py-3">
        <div
          class="row align-items-center justify-content-md-between justify-content-center"
        >
          <div
            class="d-flex align-items-center col-12 col-md-4 justify-content-center order-0"
          >
            <img
              id="logo_footer"
              src="./static/Images/logo-footer.svg"
              alt="logo"
              srcset=""
            />
            <div class="mx-3">
              <a class="footer-link" href="#">
                <p>عن المحقق الذكي</p>
              </a>
              <a class="footer-link" href="#">
                <p class="my-2">سياسة الخصوصية</p>
              </a>
              <a class="footer-link" href="#">
                <p>الشروط والأحكام</p>
              </a>
            </div>
          </div>
          <div class="col-6 col-md-4 my-4 my-md-0 order-2 order-md-1">
            <div class="social-icons d-flex justify-content-center">
              <span class="mx-1">
                <a href="#">
                  <img src="./static/Images/youtube.svg" alt="youtube" srcset="" />
                </a>
              </span>
              <span class="mx-1">
                <a href="#">
                  <img src="./static/Images/twitter.svg" alt="twitter" srcset="" />
                </a>
              </span>
              <span class="mx-1">
                <a href="#">
                  <img src="./static/Images/instagram.svg" alt="instagram" srcset="" />
                </a>
              </span>
              <span class="mx-1">
                <a href="#">
                  <img src="./static/Images/facebook.svg" alt="facebook" srcset="" />
                </a>
              </span>
            </div>
            <p
              class="text-center"
              style="font-size: 13px; color: #28494a; margin-top: 10px"
            >
              جميع الحقوق محفوظة © 2022
            </p>
          </div>
          <div
            class="align-items-center col-12 col-md-4 d-flex justify-content-center logos my-3 my-md-0 order-1 order-md-2"
          >
            <img
              style="width: 7rem"
              src="./static/Images/roaia-logo.svg"
              alt="roaia logo"
            />
            <img
              class="mx-2"
              style="width: 6rem"
              src="./static/Images/internal-logo.svg"
              alt="roaia logo"
            />
          </div>
        </div>
      </div>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
      integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
      integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
      crossorigin="anonymous"
    ></script>
    <script type="module" src="./static/Js/action.js"></script>
  </body>
</html>

website/templates/Login.html
<!DOCTYPE html>
<html lang="ar">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="./static/Images/icon.png" />
    <title>Smart Detective</title>
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="./static/Style/style.css" />
  </head>

  <body
    style="background-color: #f2f2f2; height: 100vh"
    class="align-items-center d-flex flex-column justify-content-center"
    dir="rtl"
  >
    <main
      style="background-color: #fff; border-radius: 25px; padding: 1.5rem 5rem"
      class="align-items-center d-flex flex-column justify-content-center"
    >
      <img
        src="./static/Images/logo-footer.svg"
        style="width: 10rem; margin-bottom: 1rem"
        alt="logo"
        srcset=""
      />
      <form  action="{{ url_for('views.Dashboard')}}"  >
        <div class="form-group">
          <label for="usr" style="font-size: 0.7rem; margin-right: 1.5rem"
            >اسم المستخدم</label
          >
          <input type="text" class="form-control login-input" id="usr" />
        </div>
        <div class="form-group" style="margin-top: 1rem">
          <label for="password" style="font-size: 0.7rem; margin-right: 1.5rem"
            >كلمة المرور</label
          >
          <input
            type="password"
            class="form-control login-input"
            id="password"
          />
        </div>
        <button
          id="submit_login"
          type="submit"
          class="btn btn-success"
          style="font-family: Bold; width: 100%; margin-top: 2rem"
          
        >
          دخول 
        </button>

        <a href = "{{ url_for('views.Dashboard') }}" >  دخول </a>
        <p
          class="my-3"
          style="color: #7c7c7c; font-size: 12px; text-align: center"
        >
          ليس لديك حساب ؟
        </p>
        <a href="#"
          ><p style="color: #32a05f; font-size: 9px; text-align: center">
            انقر هنا للتسجيل
          </p></a
        >
      </form>
    </main>
    <img
      src="./static/Images/internal-logo.svg"
      alt="logo"
      srcset=""
      style="width: 7rem"
    />

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
      integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
      integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
      crossorigin="anonymous"
    ></script>
    <script src="./static/Js/action.js"></script>
 
  </body>
</html>

website/templates/ProceedingPreview_OLD.html
<!DOCTYPE html>
<html lang="ar">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="./static/Images/icon.png" />
    <title>Smart Detective</title>
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="./static/Style/style.css" />
  </head>

  <body style="flex: 1;" dir="rtl">
    <header>
      <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
          <div class="navbar-brand d-flex align-items-center">
            <a href="#">
              <img
                src="./static/Images/logo.svg"
                alt="logo"
                class="d-inline-block align-text-top img-fluid"
              />
            </a>
            <div
              class="mx-2"
              style="height: 60px; width: 2px; background-color: #fff"
            ></div>
            <h3>استعراض المحضر المتشابه</h3>
          </div>
          <div class="d-flex nav-icons me-auto">
            <a href="#" class="mx-2">
              <span class="material-icons"> person </span>
            </a>
            <a href="./static/Login.html">
              <span class="material-icons"> settings_power </span>
            </a>
          </div>
        </div>
      </nav>
    </header>
    <main class="d-flex flex-column container pt-3">
      <div
        style="
          /* flex: 1; */
          height: 57vh;
          background-color: #a5b29c20;
          border-radius: 20px;
          color: #32a05f;
          padding: 2rem 3rem;
          margin-bottom: 2rem;
          margin-top: 5rem;
        "
      >
        <p>مضمون البلاغ</p>
      </div>
      <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-success">عودة</button>
      </div>
    </main>
    <footer style="margin-top: 2rem">
      <div class="container-fluid py-3">
        <div
          class="row align-items-center justify-content-md-between justify-content-center"
        >
          <div
            class="d-flex align-items-center col-12 col-md-4 justify-content-center order-0"
          >
            <img
              id="logo_footer"
              src="./static/Images/logo-footer.svg"
              alt="logo"
              srcset=""
            />
            <div class="mx-3">
              <a class="footer-link" href="#">
                <p>عن المحقق الذكي</p>
              </a>
              <a class="footer-link" href="#">
                <p class="my-2">سياسة الخصوصية</p>
              </a>
              <a class="footer-link" href="#">
                <p>الشروط والأحكام</p>
              </a>
            </div>
          </div>
          <div class="col-6 col-md-4 my-4 my-md-0 order-2 order-md-1">
            <div class="social-icons d-flex justify-content-center">
              <span class="mx-1">
                <a href="#">
                  <img src="./static/Images/youtube.svg" alt="youtube" srcset="" />
                </a>
              </span>
              <span class="mx-1">
                <a href="#">
                  <img src="./static/Images/twitter.svg" alt="twitter" srcset="" />
                </a>
              </span>
              <span class="mx-1">
                <a href="#">
                  <img src="./static/Images/instagram.svg" alt="instagram" srcset="" />
                </a>
              </span>
              <span class="mx-1">
                <a href="#">
                  <img src="./static/Images/facebook.svg" alt="facebook" srcset="" />
                </a>
              </span>
            </div>
            <p
              class="text-center"
              style="font-size: 13px; color: #28494a; margin-top: 10px"
            >
              جميع الحقوق محفوظة © 2022
            </p>
          </div>
          <div
            class="align-items-center col-12 col-md-4 d-flex justify-content-center logos my-3 my-md-0 order-1 order-md-2"
          >
            <img
              style="width: 7rem"
              src="./static/Images/roaia-logo.svg"
              alt="roaia logo"
            />
            <img
              class="mx-2"
              style="width: 6rem"
              src="./static/Images/internal-logo.svg"
              alt="roaia logo"
            />
          </div>
        </div>
      </div>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
      integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
      integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
      crossorigin="anonymous"
    ></script>
    <script type="module" src="./static/Js/action.js"></script>
  </body>
</html>